<?php

 $title = 'Add new Category';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('category', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo '<label>Name: </label>';
 echo $this->formRow($form->get('name'));

 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();