<?php

 $title = 'Edit Category';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('category', array('action' => 'edit','id'=>$this->id)));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo '<label>name: </label>';
 echo $this->formRow($form->get('name'));
 echo'<br/><br/>';
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();