<?php
 $title = 'My Categories';
 $this->headTitle($title);
 ?>
 <h2 class="page-header"><?php echo $this->escapeHtml($title); ?></h2>
 <p>
     <a href="<?php echo $this->url('category', array('action'=>'add'));?>">Add new category</a>
 </p>

 <table class="table">
 <tr>
     <th>name</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($categories as $category) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($category->name);?></td>
     <td>
         <a href="<?php echo $this->url('category',
             array('action'=>'view', 'id' => $category->id));?>">View</a>
        <a href="<?php echo $this->url('category',
             array('action'=>'edit', 'id' => $category->id));?>">Edit</a>
         <a href="<?php echo $this->url('category',
             array('action'=>'delete', 'id' => $category->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>